import { Router } from "express";
import { auth } from "../middleware/auth.js";
import { optionalAuth } from "../middleware/optionalAuth.js";
import { notifications, unreadCount, markRead, markAllRead } from "../controllers/notificationController.js";
import { requireCommunityUser, publicProfile, followUser, unfollowUser, userReviews, communityFeed, reviewById } from "../controllers/communityController.js";
import { summary, putRating, deleteRating, validateMovieSlug, validateRating } from "../controllers/ratingController.js";
import { listReviews, myReview, putReview, deleteReview, validateReview, validatePagination } from "../controllers/reviewController.js";
import { requireReview, requireComment, rootOnly, validateContent, getEngagement, putReaction, deleteReaction, listComments, createComment, editComment, deleteComment } from "../controllers/engagementController.js";

const router = Router();
import {requireCollection,collectionOwner,listCollections,createCollection,getCollection,editCollection,deleteCollection,collectionMovie,activityPrivacy,activity} from '../controllers/collectionController.js';
router.get('/me/collections',auth,validatePagination,listCollections);
router.get('/me/activity-privacy',auth,activityPrivacy);
router.put('/me/activity-privacy',auth,activityPrivacy);
router.post('/collections',auth,createCollection);
router.get('/collections/:collectionId',optionalAuth,requireCollection,getCollection);
router.patch('/collections/:collectionId',auth,requireCollection,collectionOwner,editCollection);
router.delete('/collections/:collectionId',auth,requireCollection,collectionOwner,deleteCollection);
router.put('/collections/:collectionId/movies/:slug',auth,requireCollection,collectionOwner,collectionMovie);
router.delete('/collections/:collectionId/movies/:slug',auth,requireCollection,collectionOwner,collectionMovie);
router.get('/users/:userId/collections',optionalAuth,requireCommunityUser,validatePagination,listCollections);
router.get('/users/:userId/activity',optionalAuth,requireCommunityUser,activity);
router.get("/notifications", auth, validatePagination, notifications);
router.get("/notifications/unread-count", auth, unreadCount);
router.put("/notifications/read-all", auth, markAllRead);
router.put("/notifications/:notificationId/read", auth, markRead);
router.get("/feed", optionalAuth, validatePagination, communityFeed);
router.get("/feed/following", auth, validatePagination, communityFeed);
router.get("/reviews/:reviewId", optionalAuth, requireReview, reviewById);
router.get("/users/:userId", optionalAuth, requireCommunityUser, publicProfile);
router.get("/users/:userId/reviews", optionalAuth, requireCommunityUser, validatePagination, userReviews);
router.put("/users/:userId/follow", auth, requireCommunityUser, followUser);
router.delete("/users/:userId/follow", auth, requireCommunityUser, unfollowUser);
router.get("/movies/:slug/summary", validateMovieSlug, optionalAuth, summary);
router.put("/movies/:slug/rating", validateMovieSlug, auth, validateRating, putRating);
router.delete("/movies/:slug/rating", validateMovieSlug, auth, deleteRating);
router.get("/movies/:slug/reviews", validateMovieSlug, validatePagination, optionalAuth, listReviews);
router.get("/movies/:slug/reviews/me", validateMovieSlug, auth, myReview);
router.put("/movies/:slug/review", validateMovieSlug, auth, validateReview, putReview);
router.delete("/movies/:slug/review", validateMovieSlug, auth, deleteReview);
router.get("/reviews/:reviewId/engagement", optionalAuth, requireReview, getEngagement);
router.put("/reviews/:reviewId/reaction", auth, requireReview, putReaction);
router.delete("/reviews/:reviewId/reaction", auth, requireReview, deleteReaction);
router.get("/reviews/:reviewId/comments", optionalAuth, requireReview, validatePagination, listComments);
router.post("/reviews/:reviewId/comments", auth, requireReview, validateContent, createComment);
router.get("/comments/:commentId/replies", optionalAuth, requireComment, rootOnly, validatePagination, listComments);
router.post("/comments/:commentId/replies", auth, requireComment, rootOnly, validateContent, createComment);
router.patch("/comments/:commentId", auth, requireComment, validateContent, editComment);
router.delete("/comments/:commentId", auth, requireComment, deleteComment);
export default router;
